// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ThingsAPI.Data;

namespace ThingsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171101174840_DescriptionLengthUpdate")]
    partial class DescriptionLengthUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ThingsAPI.Model.Thing", b =>
                {
                    b.Property<int>("thingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("enabled");

                    b.Property<int?>("parentthingId");

                    b.Property<string>("physicalConnection")
                        .HasMaxLength(100);

                    b.Property<string>("thingCode")
                        .HasMaxLength(50);

                    b.Property<string>("thingName")
                        .HasMaxLength(50);

                    b.HasKey("thingId");

                    b.HasIndex("parentthingId");

                    b.ToTable("Things");
                });

            modelBuilder.Entity("ThingsAPI.Model.Thing", b =>
                {
                    b.HasOne("ThingsAPI.Model.Thing", "parent")
                        .WithMany("Children")
                        .HasForeignKey("parentthingId");
                });
#pragma warning restore 612, 618
        }
    }
}
